export enum ACTIONS {
  REQUEST_DATA = 'REQUEST_DATA',
  REQUEST_END = 'REQUEST_END',
  RECEIVE_DATA = 'RECEIVE_DATA',
  REJECT_DATA = 'REJECT_DATA',
  SHOW_NOTIFICATION = 'SHOW_NOTIFICATION',
  SET_NOTIFICATION = 'SET_NOTIFICATION',
  CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION'
};